version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  node:
    build: ./infra/node
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./backend:/work
    working_dir: /work

  db:
    platform: linux/x86_64
    build: ./infra/mysql
    ports:
      - 33060:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
