version: '3.9'

services:
  workspace:
    container_name: ${PROJECT_NAME:-default}-vscode
    hostname: ${PROJECT_NAME:-default}
    build:
      context: ..
      dockerfile: .devcontainer/infra/docker/python/Dockerfile
      args:
        USER_NAME: ${USER_NAME-myzn}
        GROUP_NAME: ${GROUP_NAME-myzn}
        UID: ${UID-1000}
        GID: ${GID-1000}
        PROJECT_DIR: ${PROJECT_DIR-..}
        WORKDIR: ${WORKDIR-/opt/work}
        PYTHONPATH: ${PYTHONPATH-/opt/work}
        POETRY_HOME: ${POETRY_HOME-/opt/poetry}
        PIP_HOME: ${PIP_HOME-/opt/pip}
        SSH_HOME: ${SSH_HOME-/opt/ssh}
    working_dir: ${WORKDIR-/opt/work}
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      TZ: ${TZ-Asia/Tokyo}
      LOG_LEVEL: DEBUG
      PROJECT_NAME: docker-python
      SOURCE_VERSION: 1.0.0
      SSH_HOST: ssh-stub
      SSH_PORT: 22
      SSH_USER: root
      SSH_KEY_PATH: "/opt/ssh/id_rsa"
      PYTHONPATH: ${PYTHONPATH-/opt/work}
    volumes:
      - type: bind
        source: ../
        target: ${WORKDIR-/opt/work}
      - type: bind
        source: ../.vscode
        target: /opt/.vscode
    networks:
      - internal_network_dev

  plantuml:
    build:
      context: .
      dockerfile: ./infra/docker/pluntuml/Dockerfile
    container_name: 'plantuml'
    hostname: 'plantuml'
    ports:
      - target: 8080
        published: ${PANTUML_PUBLISHED_PORT:-8080}
    networks:
      - internal_network_dev

  ssh-stub:
    build:
      context: .
      dockerfile: ./infra/docker/ssh-stub/Dockerfile
    container_name: 'ssh-stub'
    hostname: 'ssh-stub'
    ports:
      - target: 22
        published: ${SSH_STUB_PUBLISHED_PORT:-22222}
    volumes:
      - type: bind
        source: ./infra/docker/ssh-stub/ssh/id_rsa.pub
        target: /root/.ssh/authorized_keys
      - type: bind
        source: ./infra/docker/ssh-stub/demo_scripts/docker
        target: /usr/local/bin/docker
    networks:
      internal_network_dev:
        ipv4_address: 172.20.0.10

networks:
  internal_network_dev:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
