[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["None"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gspread = "^5.11.2"
oauth2client = "^4.1.3"
spotipy = "^2.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
